### ISSUE TITLE
Server Start Error

### ISSUE THREAD

**Issue by z0mbieslayer** [pbsds/hatena-server#13]
I have twisted installed and Python2.7, it looks like it's starting up correctly but it just crashes after it says,
"Server start". Anyways, Here's what happens: `C:\Users\z0mbieslayer\Desktop\hatena-server-master>server.py
Importing modules... Done!
Initializing flipnote database... Done!
Setting up hatena site... Done!
Setting up proxy hack... Done!
Server start!

Traceback (most recent call last):
  File "C:\Users\z0mbieslayer\Desktop\hatena-server-master\server.py", line 146,
 in <module>
    reactor.listenTCP(port, site)#Hey listen!~
  File "C:\Python27\lib\site-packages\twisted\internet\posixbase.py", line 495,
in listenTCP
    p.startListening()
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 1363, in st
artListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:8080: [Errno 10
013] An attempt was made to access a socket in a way forbidden by its access per
missions.

Any help would be appreciated!

**Comment by pbsds** [comment]
It seems like you either have a process/program already using port 8080 or you might have to run the server as an admin. Skype often uses port 8080, try exiting it. Google for help to check if any other application is using the port

**Comment by pbsds** [comment]
You could also try to change the port in the config file to something else, say 8081?

**Comment by z0mbieslayer** [comment]
I got it all fixed, something else was using port 8080, thanks for helping out!
