### ISSUE TITLE
Adding different buttons to main menu

### ISSUE THREAD

**Issue by z0mbieslayer** [pbsds/hatena-server#15]
I know you may not support this any more, but every time I try and add a different button to the main menu, the button shows up, but the address I made it go to shows a 404, despite it being the correct address. Any help would be greatly appreciated :)

**Comment by z0mbieslayer** [comment]
I've managed to fix the 404, but I'm getting another error now. I'm trying to load a UGO file from pressing a button in the main menu. The button is pointed at a ULS file so it tries to load but then gives me a 340001 Could not gather data error. I've been trying my best to read the wiki, and I think I have it somewhat figured out, but I have no idea what's causing this error, because it throws no errors in the console.

**Comment by pbsds** [comment]
The DSi client is finicky, and often won't report any errors back to the server. but the console printout isn't perfect either.
Perhaps try using Wireshark or Fiddler to see if the requests made by the DSi looks like what you expect.

Have a look at [Flipnote-Collective's documentation](https://github.com/Flipnote-Collective/flipnote-studio-docs/wiki). They delved way deeper into the hatena network services than i ever did. 

I sadly never documented the ugoxml format, as i just refered to the [source](https://github.com/pbsds/hatena-server/blob/master/Hatenatools/UGO.py#L315).

**Comment by z0mbieslayer** [comment]
Thanks, I’ll try it out.
