### ISSUE TITLE
Error code: 340605 (Could not gather data)

### ISSUE THREAD

**Issue by Lugiia** [pbsds/hatena-server#21]
(I apologize if I'm not the best with this kind of stuff, I've been spending way too much time to figure out what to even do lol)

I'm using RiiConnect24's DNS server (https://github.com/RiiConnect24/DNS-Server) with an updated dns_zones.json file (to point flipnote.hatena.com to my public ip address rather than igpflip's).

I am also hosting the server with port forwarding, and I can confirm the server does work on the PC, because when I go to the address it shows a 403 Error - This proxy is only allowed to use for Flipnote Hatena for the DSi.

However, every time I try to connect to the server using my 3DS, it comes up with a Could not gather data error each time. Nothing shows up in the console either.

The hosted DNS server works, and the hatena server shows the 403, so I'm not entirely sure whats causing it. I also tried downgrading Twister but that didn't really work.

**Comment by pbsds** [comment]
I'm assuming you're using the DSi version of Flipnote Studio on the 3DS.
Try verifying that the 3DS is using the configured DNS server. Route some random name to google.com (CNAME) and check if it 
works on the 3DS browser. (This will result in a SSL domain name verification error)

**Comment by Lugiia** [comment]
Mhm, I'm using the DSiWare version of Flipnote Studio.

I can confirm the DNS server does work, I routed www.google.com to something random like 6.6.6.0 and it showed a 032-1028 "Could not display page" error.

I can also tell by checking the console log as it shows something like:
```
[DNS] {18:02:25} Received: DNS Request from: 192.168.1.3
[DNS] {18:02:25} Sent    : DNS Response to:  192.168.1.3
```

When I try connecting to the Hatena server, I can see that the console logs the DNS is sending something to the 3DS, but now its showing a different error: "20100: Unable to connect to the Internet.", despite the internet working in System Settings.

Also, if it helps: here's some more info:

• Sudomemo and IPGFlip works, my own hosted server doesnt
• When trying to connect, it shows the three green bars on the bottom right, even though its telling me its unable to connect.

**Comment by pbsds** [comment]
Try routing `conntest.nintendowifi.net` to your server as well.
[This](https://github.com/pbsds/hatena-server/blob/master/hatena.py#L55) is the code that tries to handle it.

**Comment by Lugiia** [comment]
Routing the connection test domain got rid of the 20100 error, and now its showing the 340605 one again.

**Comment by pbsds** [comment]
One last effort could be to configure the private IP instead of the public IP. You've taken all the steps I would have. I truly don't know what the issue might be.

**Comment by Lugiia** [comment]
Routing conntest.nintendowifi.net and flipnote.hatena.com to my computer's local IP address in my DNS server unfortunately didn't even make it past the connection test.

I also tried setting the proxy to my computer's local IP address, but it still shows the "Service has been discontinued" error in Flipnote Studio.

So yeah, I'm completely stumped as well. I'm not sure if it would make any difference, but I noticed that when I tried to connect th Hatena, the DSi also tried requesting something from "nat.nintendowifi.net", although I'm not sure what to do about that.

I'm probably gonna give up trying to host a server, but thanks for helping me out.

**Comment by Lugiia** [comment]
I think I found out why my server might not be working.

I've been doing some research, and found this GitHub page called "FlipnoteCollective", and it has some [documentation](https://github.com/Flipnote-Collective/flipnote-studio-docs/wiki) about the Flipnote Studio DSiWare.

Looking into the [Patching Flipnote Studio's Online Services](https://github.com/Flipnote-Collective/flipnote-studio-docs/wiki/Patching-Flipnote-Studio%27s-Online-Services) section, it mentioned that around January 17, 2018, the authentication endpoint of Flipnote Hatena closed, and in April, the nas.nintendowifi.net website that I mentioned also got shutdown.

So I do believe that nas.nintendowifi.net has something to do with this not working correctly, since that's Nintendo's authentication server for Flipnote Studio/Hatena.

**Comment by pbsds** [comment]
Yeah, i didn't think this would be the issue since the hosts file in the RiiConnect24 repo seem to point it to IPGFlip's servers.

**Comment by Lugiia** [comment]
I noticed that as well. I'll see if I can do anything about making a custom authentication server or something, but I don't think it'll work.

**Comment by Lugiia** [comment]
I am a complete idiot.

Turns out I've been trying to host my own DNS and doing this and that this entire time, until I realized you're supposed to use Sudomemo's DNS **and** set your _own_ server as a proxy.

Flipnote Hatena now works. I am really, really sorry for wasting your time.

**Comment by pbsds** [comment]
Glad it worked out :)
