### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by blobonmyknob** [pbsds/hatena-server#24]
is it okay if I work on upgrading this to python 3, or is that even possible...

**Comment by pbsds** [comment]
Go ahead, although i wonder if Twisted will make it easy :/

**Comment by blobonmyknob** [comment]
Traceback (most recent call last):
  File "server.py", line 7, in <module>
    from twisted.web import server #filehost
ImportError: No module named twisted.web
fakeblob@penguin:~/hatena-server$

**Comment by blobonmyknob** [comment]
which version of twisted must I use?

**Comment by pbsds** [comment]
Seems like the newest one should have that component.

https://twistedmatrix.com/trac/
