### ISSUE TITLE
I'm currently working on a very good thing !

### ISSUE THREAD

**Issue by Rix565** [pbsds/hatena-server#25]
I'm currently working on a conversion of the code from Python 2 to Python 3 !
Thats all.

**Comment by Rix565** [comment]
And, just : idk what does the function UgoRoot on the file hatena.py

**Comment by Rix565** [comment]
Can you explain me what does this function, because i can't get it working on python 3.
(error : [13:31:25] 192.168.1.20 got 404 when requesting "http://flipnote.hatena.com/ds/v2-eu/index.ugo")

**Comment by Rix565** [comment]
Too hard for me (because of bytes encryption that not work) , i will close this issue.

**Comment by pbsds** [comment]
Python3 changed the default string literal into UTF-8 encoded string.
I'm guessing Twisted therefore use `bytes` instead of `str`, falling back to the old python 2 behavor.
This makes the transition to python 3 rather involved.

TBH, reimplementing this in flask, sanic or aiohttp would be faster

**Comment by Rix565** [comment]
I know this is from quite a while, but I'm recoding hatena-server from scratch in Python3 - with Django. :)

**Comment by pbsds** [comment]
Cool!

**Comment by Rix565** [comment]
right now i've got channels, newest flipnotes and accounts to work ^^
