### ISSUE TITLE
Getting code errors that probably shouldn't exist. (fixed)

### ISSUE THREAD

**Issue by KingMayro** [pbsds/hatena-server#27]
I'm trying to start server.py, yet Python is telling me that parts of the code are incorrect. And I've edited it to Python's liking, but the script didn't work. 

_C:\Users\(notshowing)\OneDrive\Desktop\Other\BetterTerminal\MAINSERV>py server.py
  File "server.py", line 6
    print "Importing modules...",
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Importing modules...", end=" ")?_

And the list of errors keep going on. I know it's just with my Python so I don't know what to do. Google is no help either.

**Comment by pbsds** [comment]
Hatenatools is written in python 2, you're trying to run it with python 3.
I'm sorry that Hatenatools is as outdated as it is.
