### ISSUE TITLE
I Can't Run It

### ISSUE THREAD

**Issue by Furby667** [pbsds/hatena-server#29]
I Have A Problem When I Open server.py It Closes, Can Anybody Help?

**Comment by pbsds** [comment]
Either it crashes, or it is missing some configuration flag. Try running it from command line / powershell

**Comment by Furby667** [comment]
https://user-images.githubusercontent.com/93845494/140656646-86ea306e-df03-47c6-88de-c6d5cc4257f8.mp4

It Does This When I Open It And Nothing Happens.

**Comment by Furby667** [comment]
It Says no module named twisted.web

**Comment by pbsds** [comment]
[Version 20.3.0](https://twistedmatrix.com/trac/) was the last one to suppotrt python 2.7.

download: https://pypi.org/project/Twisted/20.3.0/

**Comment by Furby667** [comment]
I Look At The Instruction On A Website How To download pip on python 2.7.9 and when I put python in the beginning of the command it says download python from Microsoft store. Any Help?

**Comment by pbsds** [comment]
try using `py -m pip`

**Comment by Furby667** [comment]
Ok, I Tried "py -m pip" but it gave me this "'py' is not recognized as an internal or external command,
operable program or batch file."

**Comment by pbsds** [comment]
...have you not installed python?

**Comment by Furby667** [comment]
I Have Python 2.7.9 Installed

**Comment by pbsds** [comment]
Then you may have installed python in single user mode. Try reinstalling it.

**Comment by Furby667** [comment]
Ok, I Reinstalled It, Now What Do I Do?

**Comment by pbsds** [comment]
Not sure,any changes? To run the server you need python 2 and a supported version of twisted.

**Comment by Furby667** [comment]
Do I have to download pip?

**Comment by Furby667** [comment]
i did try opening setup.py twisted 20.30 using command prompt it says "ImportError: No module named setuptools"

**Comment by pbsds** [comment]
Yes, to install a module with pip you will need pip.
The general command is `pip install Twisted<=20.3.0`.
To be honest, i do not know how to install pip for python 2 on Windows in 2021, and **I do not have a Windows machine available to test on**. 
If you have multiple python installs on the system, then the `py` command is used to select between them. The `-m` switch is used to execute a module. Put together, what you'd want is something like `py -2 -m pip install Twisted<=20.3.0`. I encourage you to look for solutions online, since dependency management is not a problem specific to hatena-server. :)

**Comment by Furby667** [comment]
Do I Have to add "pip install (mypcname) --user"

**Comment by Furby667** [comment]
i tried install twisted but it gave me this "Command python setup.py egg_info failed with error code 1 in c:\users\pc\appdata\local\temp\pip_build_PC\idna
Storing debug log for failure in C:\Users\PC\pip\pip.log".

**Comment by pbsds** [comment]
And the contents of `C:\Users\PC\pip\pip.log` is?

**Comment by Furby667** [comment]
the pip.log is this "Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "C:\Python27\lib\site-packages\pip\req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "C:\Python27\lib\site-packages\pip\req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'twisted=20.3.0', 'at', '=20.3.0')".

**Comment by Furby667** [comment]
This Error Came up when i do "pip install twisted=20.3.0".

**Comment by pbsds** [comment]
Either use `<=` or `==`

**Comment by Furby667** [comment]
ok, i tried "pip install twisted==20.3.0" and it gave me errors and i tried "pip install twisted<=20.3.0" and it gave me "The system cannot find the file specified."

**Comment by pbsds** [comment]
To be honest, support for python 2 was dropped in 2020, not sure if there is much any of us can do

**Comment by Furby667** [comment]
how do i connect to my server now.

**Comment by Furby667** [comment]
its says "Server start!"

**Comment by Furby667** [comment]
and how do i create buttons on the home page on my own flipnote hatena server?

**Comment by Furby667** [comment]
how do i add icons on the index page?

**Comment by pbsds** [comment]
I basically just reverse engineered the general UGO format.
These guys examined flipnote hatena a lot more than i ever did, and have detailed how it works: https://github.com/Flipnote-Collective/flipnote-studio-docs/wiki

**Comment by Furby667** [comment]
Is It Possible for custom icons?

**Comment by Furby667** [comment]
And how do I channels in the channel button on index page?

**Comment by Furby667** [comment]
How do I create channels instead of HTML Files?

**Comment by pbsds** [comment]
I do not know, custom icons might be possible as [ntft ](https://github.com/Flipnote-Collective/flipnote-studio-docs/wiki/.ntft-image-format)images.

The [web server ](https://github.com/pbsds/hatena-server/blob/master/hatena.py#L166)constructs all its routes from the files in `hatenadir/`.
`.py` files get loaded as as a twisted resource object and routed without the filetype. `.ugoxml` files are [compiled ](https://github.com/pbsds/hatena-server/blob/master/hatena.py#L166)to `.ugo` files using [this tool](https://github.com/pbsds/Hatenatools/blob/master/UGO.py). 
Other files are simply routed as static resources.

How the ugoxml format works is for me long forgotten, but the Flipnote Collective might know.
It tries to convert back and forth between ugo and ugoxml without any loss.
if it recognizes a pattern, then it will convert it to something a bit more readable ([code](https://github.com/pbsds/Hatenatools/blob/master/UGO.py#L315)), but that is based on the shitty understanding i had of the format back then.
[These guys understand the format a lot better than me](https://github.com/Flipnote-Collective/flipnote-studio-docs/wiki/.ugo-menu-format).

Any dynamic content will have to be created in a .py file, which will construct ugo files for each request ([example](https://github.com/pbsds/hatena-server/blob/master/hatenadir/ds/v2-xx/frontpage/hotmovies.ugo.py#L57)).

**Comment by Furby667** [comment]
Does Creator Room Work?

**Comment by Furby667** [comment]
And is it possible for make a another section when you press a button on index page on my own server?

**Comment by pbsds** [comment]
Probably
