### ISSUE TITLE
Question about UGO.py compiler

### ISSUE THREAD

**Issue by Rix565** [pbsds/hatena-server#33]
Is UGO.py compiler able to compile a Creator's Room? (backend in Python)
Because I want to implement one.

**Comment by pbsds** [comment]
Most likely? I advice you to locate a creator room .ugo file and decompile it to look how it is done. I believe there was some backup or dump from the original hatena. I recieved some dumped files from JSAfive many years ago, but i do not have them anymore. 

For the logic that renders dynamic content, you need to implement it in python.

**Comment by Rix565** [comment]
Do you think you'll be able to connect to Sudomemo and dump the Creator's Room's UGO file?

**Comment by pbsds** [comment]
Haven't looked at sudomemo in many years. Unless they use some authentication scheme, connecting to it with something like `curl` should be simple.

**Comment by Rix565** [comment]
They use a authentification system with mini-flipnotes.

**Comment by pbsds** [comment]
Then adding whatever required HTTP header should be the way. Try intercepting the DSi traffic to sudomemo and look at HTTP headers. I remember using Fiddler2.
