### ISSUE TITLE
how to only load flipnotes with a specific channel on a frontpage item (aka. the python script that display)

### ISSUE THREAD

**Issue by ghost** [pbsds/hatena-server#35]
pbsds

how to filter between channels on a frontpage python script
so for example on display flipnotes the the sonic channel tag

**Comment by pbsds** [comment]
You have to add the ability to tag a flipnote. These must be stored alogside the flipnote. Then you'd have to make page for each tag. The file-based database really isn't suited for this, so implementing a SQL database would save you a lot of trouble.
