### ISSUE TITLE
Error Code 340605

### ISSUE THREAD

**Issue by Nintendo-png** [pbsds/hatena-server#38]
I'm trying to host an Flipnote DNS with auth support, so no proxy url.
According to the Flipnote Documentive, Flipnote is supposed to make an request to flipnote.hatena.com/ds/v2-us/auth. 
Instead, It shows error code 340605.
Is there any forwarders or something that forward NAS (Nintendo Auth Server) to the auth url?

**Comment by Hwilliams8548** [comment]
i was just wondering this.

**Comment by pbsds** [comment]
https://github.com/RiiConnect24/DNS-Server ?

**Comment by ghost** [comment]
yeah but it needs a /auth endpoint

**Comment by pbsds** [comment]
point it at this server at add the /auth endpoint?

**Comment by ghost** [comment]
yeah uhh idk if anyone ever implemented that

**Comment by pbsds** [comment]
this might be a good read https://github.com/pbsds/hatena-server/issues/21

**Comment by ghost** [comment]
he eventually just used sudomemo's DNS

**Comment by pbsds** [comment]
https://github.com/Flipnote-Collective/flipnote-studio-docs/wiki/Authentication

**Comment by Nintendo-png** [comment]
I made an NAS server out of PHP which works fully, but it doesn't make any requests to hatena auth

**Comment by ghost** [comment]
well the the hatena auth is stored on the same server the dsi connects to to get menus flipnotes and more

**Comment by Nintendo-png** [comment]
Back a year later. I'm still having the error 304605 issue and it seems to mean the SSL handshake is failing. I'm going to go to nds-constraint's issues tab since this has nothing to do with hatena-server.

**Comment by Nintendo-png** [comment]
Every time I try to recompile nginx with older openssl it still gives me 304605. I've also tryed older apache and older nginx before SSLv3 was deprecated.
