### ISSUE TITLE
question about authentication

### ISSUE THREAD

**Issue by ghost** [pbsds/hatena-server#39]
ok uhm im trying to make authentication work but when it tries to authenticate it doesnt send any headers back and the menu appears empty so uhm what am im doing wrong

python code:

from twisted.web import resource

class PyResource(resource.Resource):
        def __init__(self):
                resource.Resource.__init__(self)
        def render(self, request):
                request.setResponseCode(200)
                request.responseHeaders.setRawHeaders('X-DSi-Auth-Challenge', ['Nintendo'])
                request.responseHeaders.setRawHeaders('X-DSi-SID', ['temporary'])
                request.responseHeaders.setRawHeaders('X-DSi-New-Notices', ['1'])
                request.responseHeaders.setRawHeaders('X-DSi-Unread-Notices', ['1'])
                request.responseHeaders.setRawHeaders('X-DSi-Dialog-Type', ['0'])

                return "what're you looking at?"

**Comment by pbsds** [comment]
Are you sure this endpoint is being used? printing in `render` to see whether it gets called or not.

**Comment by ghost** [comment]
> Are you sure this endpoint is being used? printing in `render` to see whether it gets called or not.

how also if set the response code to 401 and try it twice you then get in but i want it to actually authenticate

**Comment by ghost** [comment]
also when i tried doing print "authenticate"
it requests it 4x and then it connects but show an empty menu and the mailbox softlocks

**Comment by pbsds** [comment]
Maybe then the headers are wrong? I believe I've seen a page by the flipnote collective about how the auth process works...

**Comment by ghost** [comment]
> Maybe then the headers are wrong? I believe I've seen a page by the flipnote collective about how the auth process works...

i can confirm they are correct as the headers are
X-DSi-Auth-challenge = nintendo 
X-DSi-SID = temporary
X-DSi-New-Notices = 1
X-DSi-Unread-Notices = 1

**Comment by pbsds** [comment]
then i don't know, never really fiddled with the auth stuff myself
