### ISSUE TITLE
Can't force working directory, may fail crash

### ISSUE THREAD

**Issue by Logrythmic24** [pbsds/hatena-server#40]
When running server.py everything goes according to plan, except there is an output of "Can't force working directory, may fail crash" before the server actually starts up.

After attempting to run server.py with "sudo" the error still persists.

Im not to sure where to go from here, any assistance is much appreciated! :)

(EDIT: spelling mistakes)

**Comment by pbsds** [comment]
It only means the server isn't able to ensure the CWD is correct. If you launch it from the correct folder then it should work

**Comment by Logrythmic24** [comment]
Awesome, thanks man! I'll look into that,
I'm running it from the Hatena server folder on my desktop but I'll continue to tinker with it.

Thanks again!
