### ISSUE TITLE
API for getting a user's FSID

### ISSUE THREAD

**Issue by angusbeefsteak** [pbsds/hatena-server#6]
Hello, I would like to know if there is any API to grab a user's FSID. I would like to write more code to the server, but I need to know if this is already on the server, or if I would need to write it myself.

**Comment by pbsds** [comment]
I have made no API on this server, so you'd have to do that yourself. I don't store users, just the uploaded flipnotes, and the database is simply a bunch of folders. (i was lazy)
This is also written using Twisted, which is getting more and more dated. If i were to redo this, then i'd go for aiohttp or sanic with uvloop. But do play around with the code and have fun
