### ISSUE TITLE
Edit images?

### ISSUE THREAD

**Issue by khang06** [pbsds/hatena-server#7]
In the hatenadir directory, there's a couple of files. I'm trying to modify the images, but they're in NTFT and NBF formats (nbf has a magic of UGAR??). I tried using Tinke to open them, but that didn't work.

**Comment by pbsds** [comment]
Oh, sorry. I haven't added the NBF cabalities to UGO.py.
Here is a script for NBF: https://gist.github.com/pbsds/9c1c0fc417f49f7ef21d
NTFT should be covered by NTFT.py in Hatenatools

**Comment by khang06** [comment]
I tried using NBF.py, but I get a "fromstring is removed" message. I had to go into Pillow and replace all fromstrings with frombytes. After that, I get:
`AttributeError: 'module' object has no attribute 'fromstring'`
Any idea how to get this to work? I'm running on Python 2.7.9.

**Comment by pbsds** [comment]
This was made to use PIL, i think Pillow is a bit too modern. You could either set up a virtualenv with PIL or just uninstall Pillow and install PIL using pip when using NBF.py

**Comment by khang06** [comment]
PIL doesn't even show up in pip, and building it from source makes an "IOError: decoder zip not available" despite having the dependencies. Also, the flipnote player appears to work just fine.

**Comment by pbsds** [comment]
The error occurs when exporting as a PNG file, which the flipnote player never does. Rewriting the WriteImage function to use newer pillow functions should do the trick
