### ISSUE TITLE
no more wiki about setting up the dsi console after running server.py

### ISSUE THREAD

**Issue by Antviau** [pbsds/hatena-server#8]
Also english is not my main language so there a few mistake or a lot.
so it's kind of hard to guess what's you need to configure the proxy.

**Comment by Antviau** [comment]
sorry in fact that's just me.
again sorry

**Comment by pbsds** [comment]
Sorry, the page was deleted by accident when reverting some past griefing. I restored it and it should be up now

**Comment by Antviau** [comment]
Thank you for responding he think it's going more easier now ans thanks (english is not my main language so there will maybe ne a few mistake)
