### ISSUE TITLE
Hatena AUTH server has closed

### ISSUE THREAD

**Issue by Gamizard** [pbsds/hatena-server#9]
[08:56:47] xxx.xxx.xxx.xxx got 403 when requesting "/ds/v2-us/auth"
debug: {'host': 'flipnote.hatena.com', 'connection': 'Keep-Alive'}

**Comment by pbsds** [comment]
:(

**Comment by crensyhanilas** [comment]
Access Denied.

**Comment by headache-booth** [comment]
**_:^)_**

**Comment by pbsds** [comment]
The DNS trick added to [this page](https://github.com/pbsds/hatena-server/wiki/How-to-connect-to-a-flipnote-server) could solve your issue
